version: '3'
services:

  ikev2-vpn:
    container_name: ikev2
    build:
      context: .
      dockerfile: Dockerfile
    image: anvarknian/ikev2:latest
    ports:
      - 4500:4500/udp
      - 500:500/udp
      - 80:80/tcp 
      # Only needed during the first run for Let's Encrypt 
      # certificates, feel free to remove it afterwards
    privileged: yes
    volumes:
      - /docker-persistent-data/ikev2/config:/config
      - /docker-persistent-data/ikev2/letsencrypt:/etc/letsencrypt
    environment:
      - DNS_SERVERS="1.1.1.1, 1.0.0.1"
      - VPNHOST=vpn.example.com
      - EMAILADDR=example@mail.com
      - VPNUSERNAME=example
      - VPNPASSWORD=example
      # Pick one of the following if you want the VPN
      # to connect automatically on certain WiFi networks
      # - INCLUDE_SSIDS="SSID1, SSID2"
      # or to connect on all WiFi networks except for these
      # - EXCLUDE_SSIDS="SSID1, SSID2"
      # ...or nothing at all
